Areas/Admin/Pages/Achievements/Create.cshtml.cs
using liaqati_master.Services.Repositories;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace liaqati_master.Areas.Admin.Pages.Achievements
{
    public class CreateModel : PageModel
    {
        private readonly IRepoAchievement _repoAchievement;

        public CreateModel(IRepoAchievement repoAchievement)
        {
            _repoAchievement = repoAchievement;
        }
        public IActionResult OnGet()
        {
            return Page();
        }
        [BindProperty]
        public Achievement Achievements { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || _repoAchievement == null)
            {
                return Page();
            }
            Achievements.Id = CommonMethods.Id_Guid();
            Achievements.UserId = "1";
            await _repoAchievement.AddEntityAsync(Achievements);
            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/Achievements/Delete.cshtml.cs
using liaqati_master.Services.Repositories;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace liaqati_master.Areas.Pages.Achievements
{
    public class DeleteModel : PageModel
    {
        private readonly IRepoAchievement _repoAchievement;

        public DeleteModel(IRepoAchievement repoAchievement)
        {
            _repoAchievement = repoAchievement;
        }

        [BindProperty]
        public Achievement Achievements { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var achievements = await _repoAchievement.GetByIDAsync(id);
            if (achievements == null)
            {
                return NotFound();
            }
            else
            {
                Achievements = achievements;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var achievements = await _repoAchievement.GetByIDAsync(id);

            if (achievements != null)
            {
                Achievements = achievements;
                await _repoAchievement.DeleteEntityAsync(Achievements);
            }

            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/Achievements/Edit.cshtml.cs
namespace liaqati_master.Areas.Admin.Pages.Achievements
{
    public class EditModel : PageModel
    {
        private readonly IRepoAchievement _repoAchievement;

        public EditModel(IRepoAchievement repoAchievement)
        {
            _repoAchievement = repoAchievement;
        }

        [BindProperty]
        public Achievement Achievements { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null || _repoAchievement == null)
            {
                return NotFound();
            }

            var achievements = await _repoAchievement.GetByIDAsync(id);
            if (achievements == null)
            {
                return NotFound();
            }
            Achievements = achievements;
            return Page();
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            Achievements.UserId = "1";
            await _repoAchievement.UpdateEntityAsync(Achievements);



            return RedirectToPage("./Index");
        }


    }
}

Areas/Admin/Pages/Articles/Create.cshtml.cs
using liaqati_master.Services.CustomValidation;
using liaqati_master.Services.CustomValidationAttribute;

namespace liaqati_master.Areas.Admin.Pages.Articles
{
    public class CreateModel : PageModel
    {
        private readonly IFormFileMang _formFileMang;
        private readonly IRepoArticles _repoArticles;
        private readonly IRepoCategory _repoCategory;

        public CreateModel(IFormFileMang formFileMang, IRepoArticles repoArticles, IRepoCategory repoCategory)
        {
            _formFileMang = formFileMang;
            _repoArticles = repoArticles;
            _repoCategory = repoCategory;
        }


        public SelectList CategoriesSelect { get; set; }
        public async Task OnGet()
        {
            CategoriesSelect = new SelectList((await _repoCategory.GetAllAsync()).Where(c => c.Target == Database.GetListOfTargets()[nameof(Article)]), nameof(Category.Id), nameof(Category.Name));

        }

        [BindProperty]
        public Article Articles { get; set; }

        [BindProperty]
        [Required(ErrorMessage = " {0} حقل مطلوب")]
        [Display(Name = "أضف صورة")]
        [AllowedExtensions(new string[] { ".png", ".jpg" }, ErrorMessage = " نوع الملف يجب أن يكون jpg , png  ")]
        [FilesMaxSize(maxFileSize: 1024 * 1024 * 2, "حجم الملف يزيد عن 2 ميغا بايت")]
        public IFormFile Image { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {

            CategoriesSelect = new SelectList((await _repoCategory.GetAllAsync()).Where(c => c.Target == Database.GetListOfTargets()[nameof(Article)]), nameof(Category.Id), nameof(Category.Name));
            Articles.Id = CommonMethods.Id_Guid();
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userid is not null)
            {
                Articles.UserId = userid;
            }
            Articles.Image = await _formFileMang.Upload(Image, "Images", "Articles");
            await _repoArticles.AddEntityAsync(Entity: Articles);
            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/Articles/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace liaqati_master.Pages.Articles
{
    public class DeleteModel : PageModel
    {
        private readonly liaqati_master.Data.LiaqatiDBContext _context;

        public DeleteModel(liaqati_master.Data.LiaqatiDBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Article Articles { get; set; }

        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id == null || _context.TblArticles == null)
            {
                return NotFound();
            }

            var articles = await _context.TblArticles.FirstOrDefaultAsync(m => m.Id == id);

            if (articles == null)
            {
                return NotFound();
            }
            else
            {
                Articles = articles;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string? id)
        {
            if (id == null || _context.TblArticles == null)
            {
                return NotFound();
            }
            var articles = await _context.TblArticles.FindAsync(id);

            if (articles != null)
            {
                Articles = articles;
                _context.TblArticles.Remove(Articles);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/Articles/Edit.cshtml.cs
namespace liaqati_master.Areas.Admin.Pages.Articles
{
    public class EditModel : PageModel
    {
        private readonly IRepoArticles _repoArticles;
        private readonly IRepoCategory _repoCategory;

        public EditModel(IRepoArticles repoArticles, IRepoCategory repoCategory)
        {
            _repoArticles = repoArticles;
            _repoCategory = repoCategory;

        }

        [BindProperty]
        public Article Articles { get; set; } = default!;
        public SelectList CategoriesSelect { get; set; }


        public async Task<IActionResult> OnGetAsync(string? id)
        {
            CategoriesSelect = new SelectList((await _repoCategory.GetAllAsync()).Where(c => c.Target == Database.GetListOfTargets()[nameof(Article)]), nameof(Category.Id), nameof(Category.Name));


            if (id == null || _repoArticles == null)
            {
                return NotFound();
            }

            var articles = await _repoArticles.GetByIDAsync(id);

            if (articles == null)
            {
                return NotFound();
            }
            Articles = articles;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            CategoriesSelect = new SelectList((await _repoCategory.GetAllAsync()).Where(c => c.Target == Database.GetListOfTargets()[nameof(Article)]), nameof(Category.Id), nameof(Category.Name));
            if (!ModelState.IsValid)
            {
                return Page();
            }
            await _repoArticles.UpdateEntityAsync(Articles);
            return RedirectToPage("./Index");
        }


    }
}

Areas/Admin/Pages/Consultations/Create.cshtml.cs
#nullable disable
namespace liaqati_master.Areas.Admin.Pages.Consultations
{
    public class CreateModel : PageModel
    {
        private readonly IRepoConsultation _IRepoConsultation;
        private readonly IRepoCategory _IRepoCategory;

        public CreateModel(IRepoConsultation repoConsultation, IRepoCategory iRepoCategory)
        {
            _IRepoConsultation = repoConsultation; _IRepoCategory = iRepoCategory;

        }


        public SelectList CategoriesSelect { get; set; }
        public async Task<IActionResult> OnGet()
        {
            CategoriesSelect = new SelectList(await _IRepoCategory.GetAllAsync(), nameof(Category.Id), nameof(Category.Name));
            return Page();
        }
        [BindProperty]
        public Consultation Consultations { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {

            Consultations.Id = CommonMethods.Id_Guid();
            if (!ModelState.IsValid)
            {
                CategoriesSelect = new SelectList(await _IRepoCategory.GetAllAsync(),
                    nameof(Category.Id), nameof(Category.Name));
                return Page();
            }
            await _IRepoConsultation.AddEntityAsync(Consultations);
            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/Consultations/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace liaqati_master.Areas.Admin.Pages.Consultations
{
    public class DeleteModel : PageModel
    {
        private readonly liaqati_master.Data.LiaqatiDBContext _context;

        public DeleteModel(liaqati_master.Data.LiaqatiDBContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Consultation Consultations { get; set; }

        public async Task<IActionResult> OnGetAsync(string? id)
        {
            if (id == null || _context.TblConsultation == null)
            {
                return NotFound();
            }

            var articles = await _context.TblConsultation.FirstOrDefaultAsync(m => m.Id == id);

            if (articles == null)
            {
                return NotFound();
            }
            else
            {
                Consultations = articles;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string? id)
        {
            if (id == null || _context.TblConsultation == null)
            {
                return NotFound();
            }
            var articles = await _context.TblConsultation.FindAsync(id);

            if (articles != null)
            {
                Consultations = articles;
                _context.TblConsultation.Remove(Consultations);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/MealPlan/Create.cshtml.cs
namespace liaqati_master.Pages.MealPlan
{
    public class CreateModel : PageModel
    {
        private readonly IRepoMealPlans _repoMealPlans;
        private readonly IRepoHealthyRecipe _repoHealthyRecipe;
        private readonly IRepoService _repoService;
        private readonly IRepoCategory _repoCategory;
        private readonly IRepoMeal_Healthy _repoMeal_Healthy;
        public CreateModel(IRepoMealPlans repoMealPlans, IRepoHealthyRecipe repoHealthyRecipe, IRepoCategory repoCategory, IRepoService repoService, IRepoMeal_Healthy repoMeal_Healthy)
        {
            _repoMealPlans = repoMealPlans;
            _repoHealthyRecipe = repoHealthyRecipe;
            _repoCategory = repoCategory;
            _repoService = repoService;
            _repoMeal_Healthy = repoMeal_Healthy;
        }
        public SelectList CatogeryName { get; set; }

        [BindProperty(SupportsGet = true)]
        public List<VmCheckBox> lstCheckBox { get; set; }


        [BindProperty(SupportsGet = true)]
        public List<VmCheckBox> lstCheckBoxDietaryType { get; set; }

        public List<string> MealType { get; set; } = Database.GetListOfMealType().Select(b => b.Value).ToList();
        public List<string> DietaryType { get; set; } = Database.GetListOfDietaryType().Select(b => b.Value).ToList();


        public string Display { get; set; } = "d-block";

        public int btnSave { get; set; }

        public async Task<IActionResult> OnGet()
        {

            foreach (var item in MealType)
            {
                lstCheckBox.Add(new VmCheckBox() { Name = item });

            }

            foreach (var item in DietaryType)
            {
                lstCheckBoxDietaryType.Add(new VmCheckBox() { Name = item });

            }










            Display = "d-block";
            btnSave = 0;


            CatogeryName = new SelectList((await _repoCategory.GetAllAsync()).Where(
                 c => c.Target == Database.GetListOfTargets()[nameof(MealPlans)]),
                 nameof(Category.Id), nameof(Category.Name));


            return Page();
        }

        public async Task<HealthyRecipe?> getHealthyRecipe(string id)
        {
            HealthyRecipe? HealthyRecipe = await _repoHealthyRecipe.GetByIDAsync(id);

            return HealthyRecipe;
        }








        [BindProperty(SupportsGet = true)]
        public MealPlans MealPlan { get; set; }


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAddAsync()
        {


            CatogeryName = new SelectList((await _repoCategory.GetAllAsync()).Where(
                 c => c.Target == Database.GetListOfTargets()[nameof(MealPlans)]),
                 nameof(Category.Id), nameof(Category.Name));
            if (!ModelState.IsValid)
            {
                return Page();
            }

            btnSave = 1;
            MealPlan.Id = CommonMethods.Id_Guid();

            MealPlan.Services!.Id = MealPlan.Id;
            MealPlan.MealType = string.Join(',', lstCheckBox.Where(ch => ch.IsChecked).Select(ch => ch.Name));
            MealPlan.DietaryType = string.Join(',', lstCheckBoxDietaryType.Where(ch => ch.IsChecked).Select(ch => ch.Name));
            MealPlan.Services.CategoryId = MealPlan.Services.CategoryId;
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (userid is not null)
            {
                MealPlan.Services.UserId = userid;
            }
            await _repoService.AddEntityAsync(MealPlan.Services);
            await _repoMealPlans.AddEntityAsync(MealPlan);
            Display = "d-block";
            return Page();
        }

        public async Task<IActionResult> OnPostAddSystemAsync(string? id)
        {
            btnSave = 1;


            MealPlans? meals = await _repoMealPlans.GetByIDAsync(id);
            if (meals is null)
            {
                return NotFound();
            }

            //List<Meal_Healthy> list = new List<Meal_Healthy>();

            //foreach (Meal_Healthy x in _context.TblMeal_Healthy.ToList())
            //{
            //    if (x.MealPlansId == id)
            //    {
            //        list.Add(x);
            //    }

            //}
            MealPlan = meals;
            MealPlan.Meal_Healthy = (await _repoMeal_Healthy.GetByMealPlansIDAsync(id)).ToList();
            MealPlan.Meal_Healthy = MealPlan.Meal_Healthy!.OrderBy(x => x.Week).ThenBy(y => y.Day).ToList();
            Display = "d-block";
            return Page();
        }




    }
}

Areas/Admin/Pages/Orders/Create.cshtml.cs
namespace liaqati_master.Areas.Admin.Pages.Orders
{
    public class CreateModel : PageModel
    {
        private readonly IRepoOrder _repoOrder;

        public CreateModel(IRepoOrder repoOrder)
        {
            _repoOrder = repoOrder;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Order Order { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            await _repoOrder.AddEntityAsync(Order);
            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/SportPrograms/Calender.cshtml
@page
@model liaqati_master.Areas.Admin.Pages.Programs.CalenderModel
@{
}
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="evo-calendar/css/evo-calendar.css" />
    <link
      rel="stylesheet"
      href="evo-calendar/css/evo-calendar.midnight-blue.css"
    />
  </head>


<div id="calendar"></div>


@section Scripts{


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="evo-calendar/js/evo-calendar.js"></script>
    
}

Areas/Admin/Pages/SportPrograms/Delete.cshtml
@page
@model liaqati_master.Areas.Admin.Pages.Programs.DeleteProgramModel
@{
}
<h3>Are you sure you want to delete this?</h3>

Areas/Admin/Pages/SportPrograms/EditAdd.cshtml
@page
@model liaqati_master.Areas.Admin.Pages.Programs.EditAddModel
@{
}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <form id="FormProgramAdd" asp-page-handler="AddSystem" method="post" class="form theme-form">
                        @*     <div asp-validation-summary="All">

                        </div>*@

                        <input asp-for="SportsPrograms.Id" hidden />


                        <div class="row">
                            <div class="col">
                                <div class="mb-3">
                                    <label asp-for="SportsPrograms.Services!.Title"></label>
                                    <input asp-for="SportsPrograms.Services!.Title" class="form-control" placeholder="">

                                </div>
                            </div>
                            <div class="col">
                                <div class="mb-3">
                                    <label asp-for="SportsPrograms.Services!.Price"></label>
                                    <input asp-for="SportsPrograms.Services!.Price" class="form-control" placeholder="">
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="mb-3">
                                    <label asp-for="SportsPrograms.Services!.Description"></label>
                                    <input asp-for="SportsPrograms.Services!.Description" class="form-control" placeholder="">
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="mb-3">
                                    <label asp-for="SportsPrograms.Length"></label>
                                    <select id="selectLength">
                                        <option value="-1">ادخل عدد اسابيع النظام الرياضي</option>
                                        <option value="1">اسبوع</option>
                                        <option value="2">اسبوعين</option>
                                        <option value="4">  اربعة اسابيع</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="mb-3">
                                    <label asp-for="SportsPrograms.Difficulty"></label>
                                    <input asp-for="SportsPrograms.Difficulty" class="form-control" placeholder="">
                                </div>
                            </div>

                            <div class="col-sm-4">
                                <div class="mb-3">
                                    <label asp-for="SportsPrograms.BodyFocus"></label>
                                    <input asp-for="SportsPrograms.BodyFocus" class="form-control" placeholder="">
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="mb-3">
                                    <label asp-for="SportsPrograms.TrainingType"></label>
                                    <input asp-for="SportsPrograms.TrainingType" class="form-control" placeholder="">
                                </div>
                            </div>
                            @*  <div class="col-sm-4">
                            <div class="mb-3">
                            <label asp-for="SportsPrograms.Services!.Category!.Name"></label>
                            <select asp-for="SportsPrograms.Services!.Category!.Id" asp-items="Model.CatogeryName">
                            <option disabled value="-1">Please Select Catogery Name</option>

                            </select>
                            </div>
                            </div>*@



                        </div>
                        <div class="container-lg my-5 d-none">
                            <div class="row justify-content-center my-5">
                                <div data-v-2eea9796="" class="col-md-12">
                                    <div class="field-value">
                                        <div class="form-label d-flex flex-row align-items-center justify-content-between">
                                            <div>المكونات</div>
                                        </div>
                                        <div class="input-group field-value">
                                            <div class="form-control">
                                                <div class="mb-3">
                                                    <label> الاسابيع</label>
                                                    <select id="selectLengthWeek" asp-for="Exercies_program.Week">
                                                        <option disabled value="-1">اختر الاسبوع</option>
                                                        @for (int x = 1; x <= Model.SportsPrograms.Length; x++)
                                                        {
                                                            <option value="@x"> الاسبوع @x</option>
                                                        }
                                                    </select>
                                                </div>
                                            </div>
                                            <select class="form-control" asp-for="Exercies_program.Day"
                                                    id="selectDays"
                                                    placeholder="اكتب شيئاً...">
                                                <option value="1">اليوم الاول</option>
                                                <option value="2">اليوم الثاني</option>
                                                <option value="3">اليوم الثالث</option>
                                                <option value="4">اليوم الرابع</option>
                                                <option value="5">اليوم الخامس</option>
                                                <option value="6">اليوم السادس</option>
                                                <option value="7">اليوم السابع</option>
                                            </select>

                                            <div class="form-control">
                                                <label> اختر التمارين الخاصة بالنظام الرياضي</label>
                                                <select asp-for="list" id="SelectExercise" aria-label="Default select example" class="js-example-rtl " multiple="multiple">
                                                </select>



                                            </div>
                                            <button id="BtnAdd"
                                                    class="text-nowrap bg-white fw-medium btn btn-outline-primary">
                                                <i class="bi bi-plus h5 fw-bold"></i>
                                            </button>
                                            <button id="BtnClipboard"
                                                    class="text-nowrap bg-white fw-medium btn btn-outline-primary rounded-start rounded-0">
                                                <i class="bi bi-clipboard h5 fw-bold"></i>
                                            </button>
                                        </div>
                                        <div class="border-top-0 rounded-bottom overflow-hidden border">
                                            <div class="p-2 bg-white d-flex gap-1 flex-wrap justify-content-start align-items-start ingredients"
                                                 style="height: 80px"
                                                 id="ingredients_container"></div>
                                        </div>
                                        <div class="small fw-bold text-end mt-1 text-muted d-flex">
                                            <div class="field-area-visible-on-hover ms-auto"
                                                 id="NoFoIngredients"></div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>







                        @*    <div class="row">
                        <div class="col-sm-4">
                        <div class="mb-3">
                        <label> اختر التمارين الخاصة بالنظام الرياضي</label>
                        <select id="SelectExercise" aria-label="Default select example" class="js-example-rtl " multiple="multiple">
                        </select>


                        </div>
                        </div>
                        </div>

                        *@


                        @*    @for (int i = 0; i < Model.SportsPrograms.Exercies_Programs?.Count; i++)
                        {

                        <input asp-for="@Model.SportsPrograms.Exercies_Programs[i].exerciseId" />
                        <div id="rowExerciesForm" class="row">
                        <div class="col">
                        <input asp-for="Exercies_program[0].Day" placeholder="اي يوم من الايام"/>
                        </div>
                        <div class="col">
                        <input asp-for="Exercies_program[0].Week" placeholder="اي اسبوع من الاسابيع" />
                        </div>
                        <div class="col">
                        <select id="selExForm" asp-for="list" placeholder="التمرين الخاص باليوم">

                        </select>
                        </div>
                        </div>
                        }

                        *@


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



@*<div class="row">
    <div class="col-sm-4">
        <div class="mb-3">
            <button class="mx-auto col-auto" type="submit"> Save </button>
        </div>
    </div>
</div>*@

















<div class="cointainer">
    @*  <div id="rowExerciesForm" class="row">
    <div class="col">
    <input asp-for="Exercies_program[0].Day" placeholder="اي يوم من الايام" />
    </div>
    <div class="col">
    <input asp-for="Exercies_program[0].Week" placeholder="اي اسبوع من الاسابيع" />
    </div>
    <div class="col">
    <select id="selExForm" asp-for="list" placeholder="التمرين الخاص باليوم">
    </select>
    </div>
    </div>
    <div id="rowExerciesForm" class="row">
    <div class="col">
    <input asp-for="Exercies_program[Model.index+3].Day" placeholder="اي يوم من الايام"/>
    </div>
    <div class="col">
    <input asp-for="Exercies_program[Model.index+3].Week" placeholder="اي اسبوع من الاسابيع" />
    </div>
    <div class="col">
    <select id="selExForm" asp-for="list" placeholder="التمرين الخاص باليوم">

    </select>
    </div>
    </div>
    *@
</div>



@section Scripts {

    <script src="~/javascript/programs.js"></script>
    <script defer src="~/jsapi/exerciseapi.js"></script>


                 }